<?php
/*
 * Functions file
 * Calls all other required files
 * PLEASE DO NOT EDIT THIS FILE IN ANY WAY
 *
 * @package parabola
 */

// variable for theme version
define ("PARABOLA_VERSION","1.4.2");

require_once(dirname(__FILE__) . "/admin/main.php"); // Load necessary admin files

//Loading include files
require_once(dirname(__FILE__) . "/includes/theme-setup.php");     // Setup and init theme
require_once(dirname(__FILE__) . "/includes/theme-styles.php");    // Register and enqeue css styles and scripts
require_once(dirname(__FILE__) . "/includes/theme-loop.php");      // Loop functions
require_once(dirname(__FILE__) . "/includes/theme-meta.php");      // Meta functions
require_once(dirname(__FILE__) . "/includes/theme-frontpage.php"); // Frontpage styling
require_once(dirname(__FILE__) . "/includes/theme-comments.php");  // Comment functions
require_once(dirname(__FILE__) . "/includes/theme-functions.php"); // Misc functions
require_once(dirname(__FILE__) . "/includes/theme-hooks.php");     // Hooks

function add_google_map() {
        return '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3075.1054561424367!2d2.6376639999999885!3d39.57977360000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x129792601612cb5b%3A0xc6ba80c95bbc7b7c!2sAvinguda+de+Sant+Ferran%2C+17%2C+07011+Palma%2C+Illes+Balears!5e0!3m2!1ses!2ses!4v1416859219734" width="400" height="300" frameborder="0" style="border:0"></iframe>';
}

add_shortcode('gmap', 'add_google_map');

?>
